### ISSUE TITLE
Unity认证开发者课程

### ISSUE THREAD

**Issue by Bennuny** [Caizc/cai-knowledge-base#1]
Unity认证开发者课程的课程看到有列目录，现在网上视频都找不到了。 不知道是否有视频呢？蟹蟹

**Comment by Caizc** [comment]
> Unity认证开发者课程的课程看到有列目录，现在网上视频都找不到了。 不知道是否有视频呢？蟹蟹

据我所知 Unity 已经取消了这个课程，目前官方也推出了很多更优质的免费视频教程，可以前往学习。
（抱歉，大半年后才留意到这个提问。）
